# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
title: Hassi
description: >-
  Something being built here.
baseurl: ""
url: "https://hytalo-bassi.github.io" 
github_username:  hytalo-bassi

theme: minima
plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll_picture_tag

sass:
  style: compressed

picture:
  source: "assets/images"
  output: "assets/images/generated"
  ignore_missing_images: "development"

include:
  - google490ec21acd5a4083.html
  - robots.txt

defaults:
  - scope:
      path: ""
    values:
      toc: true
