# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
title: Hassi Blog
description: >-
  Something being built here.
baseurl: ""
url: "https://hytalo-bassi.github.io" 
github_username:  hytalo-bassi

theme: minima
plugins:
  - jekyll-toc
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      toc: true
