title: Hassi Blog
description: >-
  O seu blog de tecnologia.
baseurl: ""
url: "https://hytalo-bassi.github.io" 
github_username:  hytalo-bassi

collections:
  authors:
    output: true
    permalink: author/:title/

theme: minima
plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll_picture_tag

sass:
  style: compressed

picture:
  source: "assets/images"
  output: "assets/images/generated"
  ignore_missing_images: "development"

include:
  - google490ec21acd5a4083.html
  - robots.txt

exclude:
  - README.md

defaults:
  - scope:
      path: ""
    values:
      toc: true
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      output: true
